# Get all users
GET http://localhost:3000/users 

# Get a user
GET http://localhost:3000/users/6907a2cf7ce1f1913f584ade

# Create user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json
{
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.smith@example.com",
  "favoriteColor": "Blue",
  "birthday": "1990-05-15",
  "phoneNumber": "+1 (555) 123-4567",
  "address": "123 Main Street, Apt 4B",
  "city": "New York"
}

# Put user
PUT http://localhost:3000/users/6907a2cf7ce1f1913f584ade HTTP/1.1
Content-Type: application/json
{
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.smith@example.com",
  "favoriteColor": "White",
  "birthday": "1990-05-15",
  "phoneNumber": "+1 (555) 123-4567",
  "address": "123 Main Street, Apt 4B",
  "city": "New York"
}

# Delete user
DELETE http://localhost:3000/users/6907a2cf7ce1f1913f584ade HTTP/1.1